<Project Sdk="MSTest.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\src\Kunc.RiotGames.Lor.DeckCodes\Kunc.RiotGames.Lor.DeckCodes.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="DeckCodesTestData.txt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
