<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Hybrid" Version="9.5.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="9.4.0" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.5" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    <PackageVersion Include="System.Text.Json" Version="9.0.5" />
    <PackageVersion Include="System.Threading.RateLimiting" Version="9.0.5" />
  </ItemGroup>
</Project>