<Project Sdk="MSTest.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\src\Kunc.RiotGames.Lol.GameClient\Kunc.RiotGames.Lol.GameClient.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="allgamedata.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
