<Project Sdk="MSTest.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\src\Kunc.RiotGames.Lor.GameClient\Kunc.RiotGames.Lor.GameClient.csproj" />
    </ItemGroup>

    <ItemGroup>

      <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <None Include="Data\**" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
