name: NuGet Publish

on:
  workflow_dispatch:
    inputs:
      tests:
        description: 'Run tests'
        required: false
        type: boolean
        default: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore  --nowarn:CS1591
    - name: Test
      if: ${{ inputs.tests }}
      env:
        LOL__APIKEY: ${{ secrets.LOL__APIKEY }}
        LOR__APIKEY: ${{ secrets.LOR__APIKEY }}
        TFT__APIKEY: ${{ secrets.TFT__APIKEY }}
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack -c Release
    - name: NuGet push
      run: dotnet nuget push --skip-duplicate --api-key ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json ./artifacts/package/release/*.nupkg
      
